<h1><?php echo $this->translate('Sign In'); ?></h1>

<div class="container-fluid">

<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form) ?>

<fieldset>
    <?php echo $this->formElementErrors($form->get('identity')) ?>

    <div class="form-group">
        <?php echo $this->formLabel($form->get('identity')) ?>
        <div class="col-sm-10">
        <?php echo $this->formInput($form->get('identity')) ?>
        </div>
    </div>

    <div class="form-group">
    <?php echo $this->formLabel($form->get('credential')) ?>
        <div class="col-sm-10">
            <?php echo $this->formInput($form->get('credential')) ?>
        </div>
    </div>

    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
    <?php endif ?>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->formButton($form->get('submit')) ?>&nbsp;
            <?php if ($this->enableRegistration) : ?>
                <?php echo $this->translate('Not registered?'); ?> <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>"><?php echo $this->translate('Sign up!'); ?></a>
            <?php endif; ?>
        </div>
    </div>

</fieldset>

<?php echo $this->form()->closeTag() ?>

</div>