<h1><?php echo $this->translate('Subscribe'); ?></h1>

<?php
if (!$this->enableRegistration) {
    echo $this->translate('Subscription is disabled');
    return;
}
$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register'));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form) ?>
<fieldset>

    <div class="form-group">
        <?php echo $this->formLabel($form->get('username')) ?>
        <div class="col-sm-10">
            <?php echo $this->formInput($form->get('username')) ?>
        </div>
    </div>

    <div class="form-group">
        <?php echo $this->formLabel($form->get('email')) ?>
        <div class="col-sm-10">
            <?php echo $this->formInput($form->get('email')) ?>
        </div>
    </div>

    <div class="form-group">
        <?php echo $this->formLabel($form->get('password')) ?>
        <div class="col-sm-10">
            <?php echo $this->formInput($form->get('password')) ?>
        </div>
    </div>

    <div class="form-group">
        <?php echo $this->formLabel($form->get('passwordVerify')) ?>
        <div class="col-sm-10">
            <?php echo $this->formInput($form->get('passwordVerify')) ?>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->formButton($form->get('submit')) ?>&nbsp;
        </div>
    </div>

<?php if ($this->redirect): ?>
    <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
<?php endif ?>

</fieldset>

<?php echo $this->form()->closeTag() ?>
