<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"
                        ><?php echo $this->translate('ZFCasts') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                        <li><a href="<?php echo $this->url('business-pages', array('action' => 'about')) ?>"
                            ><?php echo $this->translate('About') ?></a></li>
                        <li><a href="<?php echo $this->url('business-pages', array('action' => 'faq')) ?>"
                            ><?php echo $this->translate('FAQ') ?></a></li>
                        <!-- Test if the User is connected -->
                        <?php if(!$this->zfcUserIdentity()): ?>
                        <!-- display the login form -->
                        <li><a href="<?php echo $this->url('zfcuser/login') ?>"><?php echo $this->translate('Login') ?></a></li>
                        <?php else: ?>
                        <!-- display the 'display name' of the user -->
                        <?php echo $this->translate('Hello') . ' ' . $this->zfcUserIdentity()->getDisplayname(); ?>
                        <?php endif?>
                     </ul></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by ZFCasts.<?php echo $this->translate('All rights reserved.') ?>
                <a href="<?php echo $this->url('business-pages', array('action' => 'disclaimer')) ?>"
                    ><?php echo $this->translate('Disclaimer') ?></a>
                <a href="<?php echo $this->url('business-pages', array('action' => 'privacy')) ?>"
                    ><?php echo $this->translate('Privacy') ?></a>
                <a href="<?php echo $this->url('business-pages', array('action' => 'impressum')) ?>"
                    ><?php echo $this->translate('Impressum') ?></a> </p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
