<h2 id="frequently-asked-questions">Frequently Asked Questions</h2>
<h3>What's the big idea?</h3>
<p></p>
<h3>What's included?</h3>
<p>Here's what you'll get with your subscription:</p>
<ul>
    <li>Fresh screencasts every Monday</li>
    <li>Video scripts, for those who prefer reading to watching. These are available in Markdown, PDF, OpenOffice, and Microsoft Word formats.</li>
    <li>Full source code for every video, available on GitHub.</li>
</ul>
<h3>Why are they so short?</h3>
<p>My intention is to focus on one piece of Zend Framework 2, without overloading you with too much information. Similar in style to RubyTapas, each lesson aims to do one thing and do it well, without giving you too much to work with. I want you to be able to implement what you learn in each lesson straight-away. Each video comes complete with code, video transcripts and links to further information as relevant, so that you can learn more in your own time.</p>
<hr>
<h2 id="signing-up">Signing up</h2>
<h3>Is there a free trial?</h3>
<p>There isn't a free trial as such; but there are <a href="/videos/free" >a number of free videos</a> you can watch to see if a subscription is for you or not. </p>
<h3>Can I cancel my subscription if I decide it's not for me?</h3>
<p>Of course. You may cancel at any time. You won't be charged for any
    more months, and you'll continue to have access through the end of the
    last month you paid for.</p>
<h3>Can I get my money back if I don't like it?</h3>
<p>You may cancel at any time, but I am not offering refunds for the
    months you've already paid for. If you want to try before you buy,
    just take a look at the
    <a href="/videos/free">free episodes</a>.</p>
<h3>What about group discounts?</h3>
<p>Team discounts are available for groups of 10 or more
    people. <a href="mailto:subscriptions@masterzendframework.com">Contact us for details</a>.</p>
<hr>
<h2 id="watching-the-videos">Watching the videos</h2>
<h3>Can I download the videos to my iPad/phone/Raspberry Pi-powered device?</h3>
<p>At this stage, there is no download available. But it is planned for an upcoming release of the site.</p>
<h3>Is there an iTunes-compatible RSS feed?</h3>
<p>Not at this stage, but it is planned for an upcoming version of the site.</p>
<hr />
<h2 id="accounts-and-billing">Accounts and Billing</h2>
<h3>Do you offer discounts for teams?</h3>
<p>Yes. <a href="mailto:subscriptions@masterzendframework.com">Contact us</a> to find out about our team pricing.</p>
<h3>How can I update my credit card info?</h3>
<p>If you subscribed with a credit card, you can go to your
    <a href="/user/billing">account profile page</a>
    and click "Update billing info". If you subscribed with PayPal, you
    must manage your payment details from within your PayPal
    account. </p>
<hr />
<h2 id="miscellaneous">Miscellaneous</h2>
<h3>What's your Vim configuration?</h3>
<p>I'm a returning VIM afficonado, after many years away, so am making good use of <a href="http://vim.spf13.com" title="The Ultimate VIM Distribution">SPF13</a> to take care of a lot of the configuration for me. If you want to know more, then check out the site. It has a lot on offer, including Vundle, NerdTree, Surround, PIV, Tabularize and more.</p>
<h3>What tools do you use? What's your video workflow?</h3>
<p>I don't use a particularly complicated or sophisticated setup. I'm planning to write a blog post about it in the semi-near future. In short, I use Screenflow 4, GarageBand (though I'm thinking of checking out Audacity), VIM, and Chromium. It's not that sophisticated, in that I follow a simple approach of scripting each episode, recording the code, recording the audio and tidying everything up. I'll say more in an upcoming post.</p>
