<h1>Frequently Asked Questions</h1>
<h2>So What Is It?</h2>
<p>If you're a PHP developer, actually, it doesn't matter what language you use or love, if you're keen to learn all about Zend Framework 2, then this is where you're going to learn it. Every week, there's a short 5 - 10 minute video covering a topic on the framework, ranging from topics as simple as the formRow ViewHelper to configuring the ServiceManager via abstract factories. So if you want to really, deeply, truly, learn Zend Framework 2 - this is where you'll learn it. </p>
<h2>What's Included In The Subscription Price?</h2>
<p>So you know what you get, here's what you'll get with your subscription:</p>
<ul>
    <li>Fresh screencasts <em>every</em> Monday</li>
    <li>Video scripts, for those who prefer reading to watching. These are available in <em>Markdown</em>, <em>PDF</em>, <em>OpenOffice</em>, and <em>Microsoft Word</em> formats.</li>
    <li>Full source code for every video, available on GitHub.</li>
</ul>
<h2>Why Are The Videos Only 5 - 10 Minutes?</h2>
<p>My intention is to focus on one piece of Zend Framework 2, without overloading you with too much information. Similar in style to RubyTapas, each lesson aims to do one thing <strong>and do it well</strong>, without attempting to overload you. I want you to be able to implement what you learn in each lesson straight-away. Each video comes complete with code, video transcripts and links to further information as relevant, so that you can learn more in your own time.</p>
<hr>
<h2 id="signing-up">Signing up</h2>
<h3>Is There A Free Trial?</h3>
<p>There isn't a free trial as such; but there are <a href="/videos/free" >a number of free videos</a> you can watch to see if a subscription is for you or not. </p>
<h3>Can I Cancel My Subscription?</h3>
<p>Of course. You may cancel at any time. You won't be charged for any
    more months, and you'll continue to have access through the end of the
    last month you paid for.</p>
<h3>Can I Get My Money Back?</h3>
<p>You may cancel at any time, but there are no refunds for the  months you've already paid for. If you want to try before you buy, just take a look at the <a href="/videos/free">free episodes</a>.</p>
<h3>What About Group Discounts?</h3>
<p>Currently there are none; but they may be available in the future.</p>
<hr />
<h2 id="accounts-and-billing">Accounts and Billing</h2>
<h3>How Can I Update My Credit Card Details?</h3>
<p>If you subscribed with a credit card, you can go to your
    <a href="/user/billing">account profile page</a>
    and click "Update billing info". If you subscribed with PayPal, you must manage your payment details from within your PayPal account. </p>
<hr>
<h2 id="watching-the-videos">Watching The Videos</h2>
<h3>Can I Download The Videos To My iPad/iPhone/Raspberry Pi Etc?</h3>
<p>At this stage, there is no download available. But it is planned for an upcoming release of the site.</p>
<hr />
<h2 id="miscellaneous">Miscellaneous</h2>
<h3>What's Your Vim configuration?</h3>
<p>I'm a returning VIM aficionado, after many years away, so am making good use of <a href="http://vim.spf13.com" title="The Ultimate VIM Distribution">SPF13</a> to take care of a lot of the configuration for me. If you want to know more, then check out the site. It has a lot on offer, including <em>Vundle</em>, <em>NerdTree</em>, <em>Surround</em>, <em>PIV</em>, <em>Tabularize</em> and more.</p>
<h3>What Tools Do You Use? What's Your Video Workflow?</h3>
<p>I don't use a particularly complicated or sophisticated setup. I'm planning to write a blog post about it in the semi-near future. In short, I use <em>Screenflow 4</em>, <em>GarageBand</em> (though I'm thinking of checking out <em>Audacity</em>), <em>VIM</em>, and <em>Chromium.</em> It's not that sophisticated, in that I follow a simple approach of scripting each episode, recording the code, recording the audio and tidying everything up. I'll say more in an upcoming post.</p>
