<h1><?php print $this->translate('Impressum'); ?></h1>

<p>Malt Blue Matthew Setter<br />
Herboldshofer Straße 40,<br />
90765 Fürth, Germany</p>

<p>Tel.: +49 (0)152 5615 3025<br />
mail: <a href="mailto:matthew@masterzendframework.com">matthew[at]masterzendframework.com</a></p>

<p><strong>Editor:</strong><br />
Matthew Setter</p>

<p><strong>Steuernummer:</strong><br />
218 274 10125</p>

<p><strong>Ust.-IdNr.:</strong><br />
DE 286 856 351</p>

<p><strong>Haftungshinweis:</strong><br />
Alle Rechte dieses Internet-Auftritts bleiben vorbehalten. Unauthorisiertes Kopieren und Verwenden von Inhalten, Fotos und Abbildungen dieses Angebots ist verboten. Die Inhalte der Website sind ausschließlich für informative Zwecke zu nutzen. Das Kopieren, Vervielfältigen oder Verändern der Website ist nicht gestattet.</p>