<h1><?php print $this->translate('Privacy'); ?></h1>

<p>This privacy policy sets out how Master Zend Framework uses and protects any information that you
    give Master Zend Framework when you use this website. Master Zend Framework is committed to ensuring that your privacy is protected. Should we ask you to provide certain information by which you can be identified when using this website, then you can be assured that it will only be used in accordance with this privacy
    statement.</p>

<p>Master Zend Framework may change this policy from time to time by updating this page. You should
    check this page from time to time to ensure that you are happy with any changes. This policy is
    effective from 01/02/2015.</p>

<h2>What We Collect</h2>
<p>We may collect the following information:</p>

<ul>
    <li>Your Name</li>
    <li>Contact information including email address</li>
</ul>

<h2>What We Do With The Information We Gather</h2>

<p>We require this information to allow you to maintain a subscription, and
    in particular for the following reasons:</p>

<ul>
    <li>Internal record keeping.</li>
    <li>We may periodically send promotional emails about new products, special offers or other
        information which we think you may find interesting using the email address which you have
        provided.</li>
    <li>From time to time, we may also use your information to contact you for market research
        purposes.</li>
</ul>

<h2>Security</h2>
<p>We are committed to ensuring that your information is secure. In order to prevent unauthorised
    access or disclosure, we have put in place suitable physical, electronic and managerial
    procedures to safeguard and secure the information we collect online.</p>

<h2>How We Use Cookies</h2>
<p>A cookie is a small file which asks permission to be placed on your computer's hard drive. Once
    you agree, the file is added and the cookie helps analyse web traffic or lets you know when you
    visit a particular site. Cookies allow web applications to respond to you as an individual. The
    web application can tailor its operations to your needs, likes and dislikes by gathering and
    remembering information about your preferences.</p>

<p>Overall, cookies help us provide you with a better website by enabling us to monitor which pages
    you find useful and which you do not. A cookie in no way gives us access to your computer or any
    information about you, other than the data you choose to share with us.</p>

<p>You can choose to accept or decline cookies. Most web browsers automatically accept cookies, but
    you can usually modify your browser setting to decline cookies if you prefer. This may prevent
    you from taking full advantage of the website.</p>

<h2>Links To Other Websites</h2>
<p>Our website may contain links to other websites of interest. However, once you have used these
    links to leave our site, you should note that we do not have any control over that other
    website. Therefore, we cannot be responsible for the protection and privacy of any information
    which you provide whilst visiting such sites and such sites are not governed by this privacy
    statement. You should exercise caution and look at the privacy statement applicable to the
    website in question.</p>

<h2>Controlling Your Personal Information</h2>
<p>You may choose to restrict the collection or use of your personal information in the following
    ways:</p>

<ul>
    <li>if you have previously agreed to us using your personal information for direct marketing
        purposes, you may change your mind at any time by writing to or emailing us at <a href="mailto:enquiries@maltblue.com">enquiries@maltblue.com</a>
    </li>
</ul>

<p>We will not <em>sell</em>, <em>distribute </em>or <em>lease</em> your personal information to third
    parties unless we have your permission or are required by law to do so. We may use your personal
    information to send you promotional information about third parties which we think you may find
    interesting if you tell us that you wish this to happen.</p>

<p>You may request details of personal information which we hold about you under the
    <a href="http://www.legislation.gov.uk/ukpga/1998/29/contents">Data Protection Act 1998</a>.
    A small fee will be payable. If you would like a copy of the information held on you
    please write to <a href="mailto:enquiries@maltblue.com">enquiries@maltblue.com</a>.</p>

<p>If you believe that any information we are holding on you is incorrect or incomplete, please
    write to or email us as soon as possible at the above address. We will promptly correct any
    information found to be incorrect.</p>