<h1><?php print $this->translate('Manage Video'); ?></h1>

<div class="container-fluid">
    <div class="row">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('videos/manage'));
        $form->setAttribute('class', 'form-horizontal');
        $form->setAttribute('method', 'post');
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>

<?php foreach ($this->formElements as $element): ?>

        <div class="form-group">
    <?php
    $element = $form->get($element);
    echo $this->formRow($element);
    ?>
        </div>

<?php endforeach; ?>
    </div>
</div>