<h1><?php print $this->translate('All Videos'); ?></h1>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <table class="table table-bordered table-responsive">
                <tr>
                    <th>Slug</th>
                    <th>Name</th>
                    <th>Running Time</th>
                    <th>Status</th>
                    <th>Published (Date / Time)</th>
                </tr>
                <?php foreach ($this->videos as $video): ?>
                    <tr>
                        <td><a href="<?php print $this->url(
                                'administration/manage', array(
                                    'slug' => trim($video->slug)
                                )
                            ); ?>"
                               title="<?php printf('edit details of \'%s\'', trim($video->slug));?>"
                                ><?php print $video->slug;
                                ?></a></td>
                        <td><?php print $video->name; ?></td>
                        <td><?php print $video->duration; ?></td>
                        <td><?php print $video->statusId; ?></td>
                        <td><?php print $video->publishDate; ?> / <?php print
                                $video->publishTime; ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
</div>

<?php echo $this->paginationControl($this->paginator, 'Sliding', 'paginator/default',
    array('routeParams' => $this->routeParams)
)  ?>