<h1><?php echo sprintf($this->translate('Welcome to ZFCasts'), '<span
class="zf-green">',
        '</span>') ?></h1>

<div class="row">
    <div class="col-md-12">
        ZFCasts is the place for developers who want to learn all there is about Zend Framework
        2, especially if they're short on time. You get a 5 - 10 minute screencast every week,
        teaching you all there is to know, along with a host of related concepts, techniques and
        technologies.
    </div>
</div>

<div class="row">
    <p><a class="btn btn-success btn-lg" href="https://github.com/zendframework/zf2"
          target="_blank"><?php echo $this->translate('Subscribe Now For Just $9 Per/Month') ?></a>
    </p>
</div>

<div class="row">
    <h2>Sample Videos</h2>
</div>

<div class="row">
    <div class="col-md-4">
        <video width="100%"></video>
        <em>Running ZF Skeleton with PHP's Built-in Webserver</em>
    </div>
    <div class="col-md-4">
        <video width="100%"></video>
        <em>The Basics of Dependency Injection</em>
    </div>
    <div class="col-md-4">
        <video width="100%"></video>
        <em>Caching Basics</em>
    </div>
</div>

<div class="row">
    <h2>What Others Are Saying</h2>
</div>

<div class="row">
    <div class="col-md-6">
        RubyTapas is for the busy Ruby or Rails developer who is ready to reach the next level of
        code mastery. Short screencasts twice a week will introduce you to a wide variety of
        intermediate to advanced Ruby concepts and techniques, as well as core Object-Oriented
        design principles.<br/>
        <em>Matthew Setter, Software Developer</em>
    </div>
    <div class="col-md-6">
        RubyTapas is for the busy Ruby or Rails developer who is ready to reach the next level of
        code mastery. Short screencasts twice a week will introduce you to a wide variety of
        intermediate to advanced Ruby concepts and techniques, as well as core Object-Oriented
        design principles.<br/>
        <em>Matthew Setter, Software Developer</em>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        RubyTapas is for the busy Ruby or Rails developer who is ready to reach the next level of
        code mastery. Short screencasts twice a week will introduce you to a wide variety of
        intermediate to advanced Ruby concepts and techniques, as well as core Object-Oriented
        design principles.<br/>
        <em>Matthew Setter, Software Developer</em>
    </div>
    <div class="col-md-6">
        RubyTapas is for the busy Ruby or Rails developer who is ready to reach the next level of
        code mastery. Short screencasts twice a week will introduce you to a wide variety of
        intermediate to advanced Ruby concepts and techniques, as well as core Object-Oriented
        design principles.<br/>
        <em>Matthew Setter, Software Developer</em>
    </div>
</div>
